# Master Docker Compose - Data Platform 1.3
# Environment-Aware Orchestration - WSL Optimized
# Usage: ENVIRONMENT=development docker-compose up

# Include all service compositions
include:
  - path: 6-infrastructure/docker/5-postgresql/docker-compose.yaml
    env_file: .env.${ENVIRONMENT:-development}
  - path: 6-infrastructure/docker/1-kafka/docker-compose.yaml
    env_file: .env.${ENVIRONMENT:-development}
  - path: 6-infrastructure/docker/2-spark/docker-compose.yaml
    env_file: .env.${ENVIRONMENT:-development}
  - path: 6-infrastructure/docker/4-mlflow/docker-compose.yaml
    env_file: .env.${ENVIRONMENT:-development}
  - path: 6-infrastructure/docker/3-airflow/docker-compose.yaml
    env_file: .env.${ENVIRONMENT:-development}

# Dynamic network - Environment-aware
networks:
  data-platform:                           # ← default yerine
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
    labels:
      environment: "${ENVIRONMENT:-development}"
      project: "data-platform-1.3"

# WSL-Optimized Volumes
volumes:
  # Essential bind mounts only
  shared-configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./5-config
      
  shared-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
    
  # Docker managed - Better WSL performance
  shared-workspace:
    driver: local
    
  shared-workflows:
    driver: local
    
  shared-models:
    driver: local
    
  shared-data-processed:

  spark-data:
    driver: local
  
